### PR TITLE
Add support for scientific notation float literals and add inline test comments.

### PR DESCRIPTION
**Pull request by porglezomp**
So I added scientific notation float literals. It accepts both `e` and `E`, as well as `+` and `-`.
For example:

```
>>> 1e3
1000
>>> 10E-1
1
>>> 0.01e2
1
```

etc.

While I was adding this, I was trying to write a new test that seemed to fit in one of the other test files, and found it hard to add a new test without breaking the order of the existing ones, so I added an extra feature to the test harness to make inline `expect`s convenient. Wasting two lines to do

```
# Expect:
# foo
```

is just a bit annoying when you could have a concise one line expression like `# Expect = foo`.

I also changed one of the test files just as an example and to ensure that it works.

### CODE REVIEW

**Comment by porglezomp** [comment]
I changed them back so the inline ones will use `# Expect: foo` format. It uses the inline directive as long as the space following the colon isn't all whitespace. (This might not be sufficient in the future if you want to look at pure whitespace tests, but that would be a maintenance nightmare on its own.)

**Comment by porglezomp** [comment]
That commit doesn't belong in this pull request, and I don't actually know how to deal with that.

**Comment by porglezomp** [comment]
So I accidentally pushed that commit and decided to just make that part of this PR instead of messing with rewriting history.

**Comment by mcclure** [comment]
This looks good to me, I intend to merge it tonight. I really like the inline comments thing.

I have a couple extended thoughts but I think I'll put them in their own issue, your thoughts there welcome: #8

**Comment by porglezomp** [comment]
Should I push the commit for hex, octal, and binary literals for this PR?

**Comment by mcclure** [comment]
Oh! I never merged this >_>

And yes please, go ahead.

**Comment by porglezomp** [comment]
Okay, with that in this should be good to merge!

**Comment by mcclure** [comment]
I manually merged this into the unstable/0.3 branch. Thanks so much! :D

**Pull request closed without merging**
